Project fg {
  database_type: 'PostgreSQL'
  Note: '''
    # FluvialGeomorph database design.
  '''
}

// Tables
Table project {
  project_id integer [pk]
  project_name varchar(255)

  Note: '''
    # Describes the areal extent of the project.
      Also referred to as the study area.
    ## Geometry: polygon
  '''
}

Table site {
  site_id integer [pk]
  site_name varchar(225)
  project_id integer [ref: > project.project_id]

  Note: '''
    # Describes the areal extent of the site.
      Nests within project.
    ## Geometry: polygon
  '''
}

Table reach {
  reach_id integer [pk]
  reach_name varchar(255)
  site_id integer [ref: > site.site_id]

  Note: '''
    # Describes the areal extent of the reach.
      Nests within site.
    ## Geometry: polygon
  '''
}

Table survey {
  survey_id integer [pk]
  survey_name varchar(255)
  reach_id integer [ref: > reach.reach_id]
  survey_year integer
  survey_month integer
  survey_day integer

  Note: '''
    # Describes the areal extent of the elevation
      surface survey.
    ## Geometry: polygon
  '''
}

Table terrain_raster {
  terrain_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Derived raster terrain surface from a survey.
    ## Geometry: raster
  '''
}

Table cutlines {
  cutline_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents lines needed to hydrologically
      modify a terrain model.
    ## Geometry: polyline
  '''
}

Table hydro_dem {
  hydro_dem_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Hydrologically modified terrain model.
    ## Geometry: raster
  '''
}

Table contributing_area {
  contrib_area_id [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the specific catchment area for each
      pixel (in fc units).
    ## Geometry: raster
  '''
}

Table stream_network {
  stream_network_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the stream network of the study area.
    ## Geometry: polyline
  '''
}

Table flow_accumulation {
  fac_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the number of upstream pixels.
    ## Geometry: raster
  '''
}

Table flow_direction {
  fdr_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the direction of flow accross each pixel.
    ## Geometry: raster
  '''
}

Table stream_network_points {
  sn_points_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents regularly spaced points along the stream
      network.
    ## Geometry: point
  '''
}

Table gradient {
  gradient_point_id [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents slope and sinuosity characteristic values for
      stream_network_points.
    ## Geometry: point
  '''
}

Table watershed_points {
  watershed_points_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents watershed characteristic values for
      stream_network_points.
    ## Geometry: point
  '''
}

Table watershed {
  watershed_id [pk]
  reach_id integer [ref: - reach.reach_id]

  Note: '''
    # Represents the areal extent of the watershed.
  '''
}

Table flowline {
  flowline_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]


  Note: '''
    # Represents the flow path of a stream.
    ## Geometry: polyline
  '''
}

Table flowline_points {
  flowline_points_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents regularly spaced points along
      a flowline.
    ## Geometry: points
  '''
}

Table detrend {
  detrend_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents an elevation model with
      downstream slope removed.
    ## Geometry: raster
  '''
}

Table channel_slope {
  channel_slope_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the slope of the hydro_dem.
    ## Geometry: raster
  '''
}

Table centerline {
  centerline_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
  # Represents the center of the flow path.
  ## Geometry: polyline
  '''
}

Table cross_section {
  cross_section_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents cross section lines drawn
      perpendicular to the flowline.
    ## Geometry: polyline
  '''
}

Table dimensions_L1 {
  l1_dims_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents cross section dimensions
      at level 1.
    ## Geometry: polyline
  '''
}

Table dimensions_L2 {
  l2_dims_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents cross section dimensions
      at level 2.
    ## Geometry: polyline
  '''
}

Table dimensions_L3 {
  l3_dims_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents cross section dimensions
      at level 3.
    ## Geometry: polyline
  '''
}

Table bankfull_area {
  bankfull_area_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the channel area typically
      inundated during bankfull events.
    ## Geometry: polygon
  '''
}

Table banklines {
  banklines_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the stream banks at bankfull.
    ## Geometry: polyline
  '''
}

Table bankline_points {
  bankline_points_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents regularly spaced points along
      the banklines.
    ## Geometry: point
  '''
}

Table features {
  features_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents key stream features.
    ## Geometry: point
  '''
}

Table riffle {
  riffle_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents riffle stream features.
    ## Geometry: polyline
  '''
}

Table valleyline {
  valleyline_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the trend line of the down-
      valley axis.
    ## Geometry: polyline
  '''
}

Table loop_points {
  loop_points_id integer [pk]
  reach_id integer [ref: - reach.reach_id]
  survey_id integer [ref: - survey.survey_id]

  Note: '''
    # Represents the key planform loop and
      bend locations.
    ## Geometry: polyline
  '''
}

TableGroup project_dev {
  project
  site
  reach
  watershed
}

TableGroup create_terrain {
  survey
  terrain_raster
  cutlines
  hydro_dem
  contributing_area
  flow_accumulation
  flow_direction
  channel_slope
}

TableGroup level_1 {
  flowline
  flowline_points
  detrend
  centerline
  cross_section
  features
  dimensions_L1
}

TableGroup level_2 {
  bankfull_area
  banklines
  bankline_points
  riffle
  dimensions_L2
}

TableGroup level_3 {
  valleyline
  loop_points
  dimensions_L3
}
